/**
 * Settings API routes.
 * Provides endpoint to persist API key to server-side .env.local.
 */
import { Router } from 'express';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ENV_LOCAL_PATH = path.join(__dirname, '..', '.env.local');

const router = Router();

/**
 * POST /api/settings/env-key
 * Write API key and endpoint config to server/.env.local
 * so settings survive server restart.
 *
 * Body: { apiKey, baseURL?, model? }
 */
router.post('/env-key', (req, res) => {
  try {
    const { apiKey, baseURL, model } = req.body || {};
    if (!apiKey || typeof apiKey !== 'string' || !apiKey.trim()) {
      return res.status(400).json({ error: 'apiKey 不能为空' });
    }

    const lines = [
      `# Auto-generated by study-assistant settings (${new Date().toISOString()})`,
      `OPENAI_API_KEY=${apiKey.trim()}`,
    ];
    if (baseURL && typeof baseURL === 'string' && baseURL.trim()) {
      lines.push(`OPENAI_BASE_URL=${baseURL.trim()}`);
    }
    if (model && typeof model === 'string' && model.trim()) {
      lines.push(`OPENAI_MODEL=${model.trim()}`);
    }

    fs.writeFileSync(ENV_LOCAL_PATH, lines.join('\n') + '\n', 'utf-8');
    console.log('[settings] 已写入 .env.local');

    res.json({ success: true, path: ENV_LOCAL_PATH });
  } catch (err) {
    console.error('[settings] 写入 .env.local 失败:', err.message);
    res.status(500).json({ error: '写入失败: ' + err.message });
  }
});

/**
 * GET /api/settings/env-key
 * Check if server-side .env.local exists and has a key.
 */
router.get('/env-key', (req, res) => {
  try {
    const exists = fs.existsSync(ENV_LOCAL_PATH);
    if (!exists) {
      return res.json({ exists: false, keySet: false });
    }
    const content = fs.readFileSync(ENV_LOCAL_PATH, 'utf-8');
    const hasKey = /^OPENAI_API_KEY=/m.test(content);
    res.json({ exists: true, keySet: hasKey });
  } catch {
    res.json({ exists: false, keySet: false });
  }
});

export default router;
